branches:
  only:
    - hexo

language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules

install:
  - npm install
  - cd ${FOLDER_SOURCE}
  - rm $(ls -F | grep [^/]$)
  - echo ${DOMAIN} > CNAME
  - cd ..
script:
  - npm run build
  - cd ${FOLDER_TARGET}
  - git init
  - git config user.name ${UID}
  - git config user.email ${EMAIL}
  - git add .
  - git commit -m "${MESSAGE}"
  - git push --force --quiet https://${TOKEN}@${GIT_URI}.git master:${BRANCH}
