branches:
  only:
    - hexo

language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules

before_install:
  - export TZ=Asia/Chongqing
install:
  - npm install
  - cd source/
  - rm $(ls -F | grep [^/]$)
  - cd ..
script:
  - npm run build
deploy:
  provider: pages
  on:
    branch: hexo
  skip_cleanup: true
  local_dir: public/
  fqdn: fcc-cd.dev
  target_branch: master
  token: ${TOKEN}
